# Generated by Django 3.0.14 on 2021-04-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplieruser',
            name='brand_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Brand name'),
        ),
    ]
