# Generated by Django 3.0.14 on 2021-04-22 15:42

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_auto_20210422_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='profilemenuitem',
            name='page',
            field=modelcluster.fields.ParentalKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='userauth.ProfileMenu'),
            preserve_default=False,
        ),
    ]
