# Generated by Django 3.0.14 on 2021-04-22 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_auto_20210422_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemenuitem',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='profilemenuitem',
            name='is_manager',
        ),
        migrations.RemoveField(
            model_name='profilemenuitem',
            name='is_supplier',
        ),
    ]
