# Generated by Django 3.0.14 on 2021-05-09 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0008_auto_20210509_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
