# Generated by Django 3.0.14 on 2021-05-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0010_auto_20210509_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_name',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='First name'),
        ),
    ]
