# Generated by Django 3.0.14 on 2021-05-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0011_address_address_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='address',
            name='is_primary',
            field=models.BooleanField(blank=True, default='False', null=True, unique=True, verbose_name='Primary address'),
        ),
    ]
