# Generated by Django 3.0.14 on 2021-05-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0012_auto_20210509_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='is_primary',
            field=models.BooleanField(blank=True, default='False', null=True, verbose_name='Primary address'),
        ),
    ]
