# Generated by Django 3.0.14 on 2021-04-22 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210422_1453'),
        ('userauth', '0002_auto_20210422_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userauth.CustomerUser'),
        ),
        migrations.AlterField(
            model_name='pickuppoint',
            name='managers',
            field=models.ManyToManyField(blank=True, to='userauth.ManagerUser'),
        ),
        migrations.AlterField(
            model_name='pickuppoint',
            name='suppliers',
            field=models.ManyToManyField(blank=True, to='userauth.SupplierUser'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='userauth.SupplierUser'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
