# Generated by Django 3.0.14 on 2021-05-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210504_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuppoint',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
