# Generated by Django 3.0.14 on 2021-05-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_pickuppoint_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_started',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(),
        ),
    ]
