# Generated by Django 3.0.14 on 2021-05-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=None, height_field='400', upload_to='', width_field='600'),
        ),
    ]
