# Generated by Django 3.0.14 on 2021-05-09 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0011_address_address_name'),
        ('store', '0011_auto_20210508_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userauth.Address'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
