# Generated by Django 3.0.14 on 2021-04-26 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_sitesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='navbar_no_backdrop',
        ),
    ]
