# Generated by Django 3.0.14 on 2021-05-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20210509_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='bullshit',
            field=models.CharField(default='bullshit', max_length=10),
        ),
        migrations.AddField(
            model_name='homepage',
            name='bullshit2',
            field=models.CharField(default='anticonstitutionnellement', max_length=50),
        ),
    ]
