# Generated by Django 3.0.14 on 2021-05-15 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20210515_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='bullshit',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='bullshit2',
        ),
    ]
