# Generated by Django 3.0.14 on 2021-04-25 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0046_auto_20210425_0828'),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfilePage',
        ),
    ]
