# Generated by Django 3.0.14 on 2021-05-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemenuitem',
            name='item_page',
            field=models.CharField(default='/', help_text='the relative url of the target page', max_length=30),
        ),
    ]
