# Generated by Django 3.0.14 on 2021-05-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20210506_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemenuitem',
            old_name='item_page',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='profilemenuitem',
            name='slug',
        ),
        migrations.AddField(
            model_name='profilemenuitem',
            name='title',
            field=models.CharField(default='', max_length=30),
        ),
    ]
