# Generated by Django 3.0.14 on 2021-05-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20210506_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemenuitem',
            name='url',
            field=models.CharField(default='/', help_text='the relative url of the target page', max_length=100),
        ),
    ]
